apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: affine
  name: affine
spec:
  ports:
    - name: "3010"
      port: 3010
      targetPort: 3010
    - name: "5555"
      port: 5555
      targetPort: 5555
  selector:
    io.kompose.service: affine
