apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    io.kompose.service: affine
  name: affine
spec:
  lookupPolicy:
    local: false
  tags:
    - from:
        kind: DockerImage
        name: ghcr.io/toeverything/affine-graphql:stable
      name: stable
      referencePolicy:
        type: ""
